services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-microservice:
    build: ./auth-microservice
    container_name: auth
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8001:8000"

  league-microservice:
    build: ./league-microservice
    container_name: league
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
      - VUE_APP_LEAGUE_API=${VUE_APP_LEAGUE_API}
    depends_on:
      - mongo
    ports:
      - "8002:8000"

  club-microservice:
    build: ./club-microservice
    container_name: club
    env_file:
      - .env
    environment:
      - VUE_APP_CLUB_API=${VUE_APP_CLUB_API}
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8003:8000"

  match-microservice:
    build: ./match-microservice
    container_name: match
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8004:8000"

  footballer:
    build: ./footballer-microservice
    container_name: footballer
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8005:8000"

  transfers:
    build: ./transfers-microservice
    container_name: transfers
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8006:8000"

  table:
    build: ./table-microservice
    container_name: table
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8007:8000"

  match-review:
    build: ./match-review-microservice
    container_name: match-review
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    ports:
      - "8008:8000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    depends_on:
      - auth-microservice
      - mongo
      - league-microservice
      - club-microservice
      - match-microservice
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
      - VUE_APP_LEAGUE_API=${VUE_APP_LEAGUE_API}
      - VUE_APP_CLUB_API=${VUE_APP_CLUB_API}

volumes:
  mongo-data: