services:
  auth-microservice:
    build: ./auth-microservice
    container_name: auth
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8001:8000"

  league-microservice:
    build: ./league-microservice
    container_name: league
    env_file:
      - .env
    depends_on:
      - auth-microservice
    environment:
      - MONGO_URI=${MONGO_URI}
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
    ports:
      - "8002:8000"

  club-microservice:
    build: ./club-microservice
    container_name: club
    env_file:
      - .env
    depends_on:
      - league-microservice
    environment:
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8003:8000"

  match-microservice:
    build: ./match-microservice
    container_name: match
    env_file:
      - .env
    depends_on:
      - league-microservice
      - club-microservice
    environment:
      - MONGO_URI=${MONGO_URI}
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
    ports:
      - "8004:8000"

  table-microservice:
    build: ./table-microservice
    container_name: table
    env_file:
      - .env
    depends_on:
      - match-microservice
      - league-microservice
      - club-microservice
    environment:
      - MONGO_URI=${MONGO_URI}
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
    ports:
      - "8005:8000"
      
  footballer-microservice:
    build: ./footballer-microservice
    container_name: footballer
    env_file:
      - .env
    depends_on:
      - hardhat
    environment:
      - MONGO_URI=${MONGO_URI}
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
    ports:
      - "8006:8000"

  transfers-microservice:
    build: ./transfers-microservice
    container_name: transfers
    env_file:
      - .env
    depends_on:
      - footballer-microservice
      - hardhat
    environment:
      - MONGO_URI=${MONGO_URI}
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
    ports:
      - "8007:8000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    depends_on:
      - auth-microservice
      - league-microservice
      - club-microservice
      - match-microservice
      - table-microservice
      - footballer-microservice
      - transfers-microservice
      - hardhat
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_AUTH_API=${VUE_APP_AUTH_API}
      - VUE_APP_LEAGUE_API=${VUE_APP_LEAGUE_API}
      - VUE_APP_CLUB_API=${VUE_APP_CLUB_API}
      - VUE_APP_TABLE_API=${VUE_APP_TABLE_API}
      - VUE_APP_FOOTBALLER_API=${VUE_APP_FOOTBALLER_API}
      - VUE_APP_TRANSFER_API=${VUE_APP_TRANSFER_API}
      - VUE_APP_CONTRACT_ADDRESS=${VUE_APP_CONTRACT_ADDRESS}

  hardhat:
    build: ./blockchain
    container_name: hardhat
    ports:
      - "8545:8545"
